os: linux
dist: trusty
language: c
#
jobs:
  include:

    - name: "Ub 16.04 -- gcc 5.4.0"
      dist: xenial
      env: MATRIX_EVAL="CC=gcc"

    - name: "Ub 16.04 -- clang 7.0.0"
      dist: xenial
      env: MATRIX_EVAL="CC=clang"

#
before_install:
  - sudo apt-get install -y regina-rexx libregina3-dev
  - sudo apt-get install -y binutils binutils-dev
  - eval "${MATRIX_EVAL}"

#
before_script:
  - util/bldlvlck
  - ./autogen.sh
  - ./configure --enable-regina-rexx
  - bash -c '${CC} --version'

#
script:
  - make -j 2
  - make check
