os: linux
dist: bionic
language: c
#
jobs:
  include:

    - name: "Ubuntu 18.04 -- gcc 7.5.0"
      dist: bionic
      env: MATRIX_EVAL="CC=gcc"

    - name: "Ubuntu 18.04 -- clang 7.0.0"
      dist: bionic
      env: MATRIX_EVAL="CC=clang"

#
before_install:
  - sudo apt-get install -y regina-rexx libregina3-dev
  - sudo apt-get install -y binutils binutils-dev
  - eval "${MATRIX_EVAL}"

#
before_script:
  - util/bldlvlck
  - ./autogen.sh
  - mkdir build
  - cd build
  - ../configure --enable-regina-rexx
  - bash -c '${CC} --version'

#
script:
  - make -j 2
  - make check
