#
language: c

#
jobs:
  include:
    - name: "Ubuntu 16.04 -- gcc 5.4.0"
      os: linux
      dist: xenial
      env: MATRIX_EVAL="CC=gcc"

    - name: "Ubuntu 16.04 -- clang 7.0.0"
      os: linux
      dist: xenial
      env: MATRIX_EVAL="CC=clang"

    - name: "Ubuntu 18.04 -- gcc 7.5.0"
      os: linux
      dist: bionic
      env: MATRIX_EVAL="CC=gcc"

    - name: "Ubuntu 18.04 -- Clang 7.0.0"
      os: linux
      dist: bionic
      env: MATRIX_EVAL="CC=clang"

    - name: "Ubuntu 20.04 -- gcc 9.3.0"
      os: linux
      dist: focal
      env: MATRIX_EVAL="CC=gcc"

    - name: "Ubuntu 20.04 -- Clang 11"
      os: linux
      dist: focal
      env: MATRIX_EVAL="CC=clang-11"

#
before_install:
  - echo $TRAVIS_OS_NAME
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo $TRAVIS_DIST                                 ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y regina-rexx libregina3-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y binutils binutils-dev     ; fi
  - 'if [ "$TRAVIS_DIST"   = "focal" ]; then sudo apt install -y clang-11; fi'

#
before_script:
  - eval "${MATRIX_EVAL}"
  - bash -c '${CC} --version'
  - util/bldlvlck
  - ./autogen.sh
  - ./configure --enable-regina-rexx

#
script:
  - make -j 2
  - make check
